project: 
  type: website
  output-dir: docs
website: 
  title: "My projects"
  site-url: https://username.github.io/repo-name/
  repo-url: https://github.com/username/repo-name
  navbar: 
    left:
      - href: index.qmd
        text: index
      - href: Final Project.qmd
        text: Final Project
      - href: Data set.qmd
        text: Data set
      - href: Code-Page.qmd
        text: Code-Page

format:
  html:
    theme: cosmo